# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'timer_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TradingBotV1(object):
    def setupUi(self, TradingBotV1):
        TradingBotV1.setObjectName("TradingBotV1")
        TradingBotV1.resize(800, 600)
        TradingBotV1.setMinimumSize(QtCore.QSize(800, 600))
        TradingBotV1.setMaximumSize(QtCore.QSize(800, 600))
        TradingBotV1.setSizeIncrement(QtCore.QSize(800, 600))
        TradingBotV1.setBaseSize(QtCore.QSize(800, 600))
        TradingBotV1.setStyleSheet("background-color: white;\n"
"")
        self.centralwidget = QtWidgets.QWidget(TradingBotV1)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 290, 771, 251))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.outputArea = QtWidgets.QTextEdit(self.layoutWidget)
        self.outputArea.setStyleSheet("background-color: white;\n"
"")
        self.outputArea.setObjectName("outputArea")
        self.verticalLayout.addWidget(self.outputArea)
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(10, 10, 191, 21))
        self.textEdit.setStyleSheet("background-color: white;\n"
"")
        self.textEdit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textEdit.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(10, 40, 191, 21))
        self.textEdit_2.setStyleSheet("background-color: white;\n"
"")
        self.textEdit_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textEdit_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textEdit_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_3.setGeometry(QtCore.QRect(10, 100, 191, 21))
        self.textEdit_3.setStyleSheet("background-color: white;\n"
"")
        self.textEdit_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textEdit_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textEdit_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_3.setObjectName("textEdit_3")
        self.textEdit_4 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_4.setGeometry(QtCore.QRect(10, 70, 191, 21))
        self.textEdit_4.setStyleSheet("background-color: white;\n"
"")
        self.textEdit_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textEdit_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textEdit_4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_4.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_4.setObjectName("textEdit_4")
        self.textEdit_5 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_5.setGeometry(QtCore.QRect(10, 190, 191, 21))
        self.textEdit_5.setStyleSheet("background-color: white;\n"
"")
        self.textEdit_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textEdit_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textEdit_5.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_5.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_5.setObjectName("textEdit_5")
        self.textEdit_6 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_6.setGeometry(QtCore.QRect(10, 160, 191, 21))
        self.textEdit_6.setStyleSheet("background-color: white;\n"
"")
        self.textEdit_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textEdit_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textEdit_6.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_6.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_6.setObjectName("textEdit_6")
        self.textEdit_7 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_7.setGeometry(QtCore.QRect(10, 130, 191, 21))
        self.textEdit_7.setStyleSheet("background-color: white;\n"
"")
        self.textEdit_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textEdit_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textEdit_7.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_7.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_7.setObjectName("textEdit_7")
        self.textEdit_8 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_8.setGeometry(QtCore.QRect(10, 250, 191, 21))
        self.textEdit_8.setStyleSheet("background-color: white;\n"
"")
        self.textEdit_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textEdit_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textEdit_8.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_8.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_8.setObjectName("textEdit_8")
        self.returnPressed = QtWidgets.QPushButton(self.centralwidget)
        self.returnPressed.setGeometry(QtCore.QRect(280, 250, 111, 24))
        self.returnPressed.setObjectName("returnPressed")
        self.entryOffsetLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.entryOffsetLineEdit.setGeometry(QtCore.QRect(210, 70, 61, 21))
        self.entryOffsetLineEdit.setStyleSheet("background-color: white;\n"
"")
        self.entryOffsetLineEdit.setObjectName("entryOffsetLineEdit")
        self.minProfitLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.minProfitLineEdit.setGeometry(QtCore.QRect(210, 100, 61, 21))
        self.minProfitLineEdit.setStyleSheet("background-color: white;\n"
"")
        self.minProfitLineEdit.setObjectName("minProfitLineEdit")
        self.trailingDropLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.trailingDropLineEdit.setGeometry(QtCore.QRect(210, 130, 61, 21))
        self.trailingDropLineEdit.setStyleSheet("background-color: white;\n"
"")
        self.trailingDropLineEdit.setObjectName("trailingDropLineEdit")
        self.trailingStopBelowLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.trailingStopBelowLineEdit.setGeometry(QtCore.QRect(210, 160, 61, 21))
        self.trailingStopBelowLineEdit.setStyleSheet("background-color: white;\n"
"")
        self.trailingStopBelowLineEdit.setObjectName("trailingStopBelowLineEdit")
        self.trailingStopBetweenLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.trailingStopBetweenLineEdit.setGeometry(QtCore.QRect(210, 190, 61, 21))
        self.trailingStopBetweenLineEdit.setStyleSheet("background-color: white;\n"
"")
        self.trailingStopBetweenLineEdit.setObjectName("trailingStopBetweenLineEdit")
        self.megaStopLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.megaStopLineEdit.setGeometry(QtCore.QRect(210, 250, 61, 21))
        self.megaStopLineEdit.setObjectName("megaStopLineEdit")
        self.trailingStopAboveLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.trailingStopAboveLineEdit.setGeometry(QtCore.QRect(210, 220, 61, 21))
        self.trailingStopAboveLineEdit.setStyleSheet("background-color: white;\n"
"")
        self.trailingStopAboveLineEdit.setObjectName("trailingStopAboveLineEdit")
        self.textEdit_9 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_9.setGeometry(QtCore.QRect(10, 220, 191, 21))
        self.textEdit_9.setStyleSheet("background-color: white;\n"
"")
        self.textEdit_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textEdit_9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textEdit_9.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_9.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_9.setObjectName("textEdit_9")
        self.leverageLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.leverageLineEdit.setGeometry(QtCore.QRect(210, 40, 61, 21))
        self.leverageLineEdit.setStyleSheet("background-color: white;\n"
"")
        self.leverageLineEdit.setObjectName("leverageLineEdit")
        self.tradeAmountLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.tradeAmountLineEdit.setGeometry(QtCore.QRect(210, 10, 61, 21))
        self.tradeAmountLineEdit.setStyleSheet("background-color: white;\n"
"")
        self.tradeAmountLineEdit.setObjectName("tradeAmountLineEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 791, 281))
        self.label.setMinimumSize(QtCore.QSize(781, 0))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("IMG_0102.JPG"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.lblStatus = QtWidgets.QLabel(self.centralwidget)
        self.lblStatus.setGeometry(QtCore.QRect(380, 80, 51, 16))
        self.lblStatus.setObjectName("lblStatus")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(640, 10, 121, 247))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.timeEditStart = QtWidgets.QTimeEdit(self.verticalLayoutWidget)
        self.timeEditStart.setObjectName("timeEditStart")
        self.verticalLayout_2.addWidget(self.timeEditStart)
        self.btnAddSchedule = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnAddSchedule.setObjectName("btnAddSchedule")
        self.verticalLayout_2.addWidget(self.btnAddSchedule)
        self.timeEditStop = QtWidgets.QTimeEdit(self.verticalLayoutWidget)
        self.timeEditStop.setObjectName("timeEditStop")
        self.verticalLayout_2.addWidget(self.timeEditStop)
        self.btnRemoveSchedule = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnRemoveSchedule.setObjectName("btnRemoveSchedule")
        self.verticalLayout_2.addWidget(self.btnRemoveSchedule)
        self.listSchedule = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.listSchedule.setObjectName("listSchedule")
        self.verticalLayout_2.addWidget(self.listSchedule)
        self.stopBotButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.stopBotButton.setObjectName("stopBotButton")
        self.verticalLayout_2.addWidget(self.stopBotButton)
        self.startBotButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.startBotButton.setObjectName("startBotButton")
        self.verticalLayout_2.addWidget(self.startBotButton)
        self.label.raise_()
        self.layoutWidget.raise_()
        self.textEdit.raise_()
        self.textEdit_2.raise_()
        self.textEdit_3.raise_()
        self.textEdit_4.raise_()
        self.textEdit_5.raise_()
        self.textEdit_6.raise_()
        self.textEdit_7.raise_()
        self.textEdit_8.raise_()
        self.returnPressed.raise_()
        self.entryOffsetLineEdit.raise_()
        self.minProfitLineEdit.raise_()
        self.trailingDropLineEdit.raise_()
        self.trailingStopBelowLineEdit.raise_()
        self.trailingStopBetweenLineEdit.raise_()
        self.megaStopLineEdit.raise_()
        self.trailingStopAboveLineEdit.raise_()
        self.textEdit_9.raise_()
        self.leverageLineEdit.raise_()
        self.tradeAmountLineEdit.raise_()
        self.lblStatus.raise_()
        self.verticalLayoutWidget.raise_()
        TradingBotV1.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TradingBotV1)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        TradingBotV1.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TradingBotV1)
        self.statusbar.setObjectName("statusbar")
        TradingBotV1.setStatusBar(self.statusbar)

        self.retranslateUi(TradingBotV1)
        QtCore.QMetaObject.connectSlotsByName(TradingBotV1)

    def retranslateUi(self, TradingBotV1):
        _translate = QtCore.QCoreApplication.translate
        TradingBotV1.setWindowTitle(_translate("TradingBotV1", "TradingBotV1.2"))
        self.textEdit.setHtml(_translate("TradingBotV1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">TRADE_AMOUNT_USD</span></p></body></html>"))
        self.textEdit_2.setHtml(_translate("TradingBotV1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">LEVERAGE</span></p></body></html>"))
        self.textEdit_3.setHtml(_translate("TradingBotV1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">MINIMUM_REQUIRED_PROFIT_USD </span></p></body></html>"))
        self.textEdit_4.setHtml(_translate("TradingBotV1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">ENTRY_TRIGGER_OFFSET_USD</span></p></body></html>"))
        self.textEdit_5.setHtml(_translate("TradingBotV1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">TRAILING_STOP_60 - 100</span></p></body></html>"))
        self.textEdit_6.setHtml(_translate("TradingBotV1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">TRAILING_STOP_BELOW_60</span></p></body></html>"))
        self.textEdit_7.setHtml(_translate("TradingBotV1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">TRAILING_DROP_PERCENT</span></p></body></html>"))
        self.textEdit_8.setHtml(_translate("TradingBotV1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">MEGA_STOP_TRIGGER_USD 1</span></p></body></html>"))
        self.returnPressed.setText(_translate("TradingBotV1", "ENTER Parameter"))
        self.textEdit_9.setHtml(_translate("TradingBotV1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">TRAILING_STOP &lt; 100</span></p></body></html>"))
        self.lblStatus.setText(_translate("TradingBotV1", "Status"))
        self.btnAddSchedule.setText(_translate("TradingBotV1", "Zeit hinzufügen"))
        self.btnRemoveSchedule.setText(_translate("TradingBotV1", "Zeit entfernen"))
        self.stopBotButton.setText(_translate("TradingBotV1", "STOP Bot"))
        self.startBotButton.setText(_translate("TradingBotV1", "START Bot"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TradingBotV1 = QtWidgets.QMainWindow()
    ui = Ui_TradingBotV1()
    ui.setupUi(TradingBotV1)
    TradingBotV1.show()
    sys.exit(app.exec_())
